/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.alyrow.gdx.particle;

import com.badlogic.gdx.Game;
import com.badlogic.gdx.Gdx;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application;
import com.badlogic.gdx.backends.lwjgl3.Lwjgl3ApplicationConfiguration;
import com.badlogic.gdx.graphics.GL20;
import com.badlogic.gdx.graphics.OrthographicCamera;
import com.badlogic.gdx.graphics.g2d.SpriteBatch;
import com.badlogic.gdx.math.Rectangle;
import io.github.alyrow.gdx.particle.physics.BrownianForce;
import io.github.alyrow.gdx.particle.physics.Fan;
import io.github.alyrow.gdx.particle.physics.PathFollow;
import io.github.alyrow.gdx.particle.physics.PhysicManager;
import io.github.alyrow.gdx.particle.physics.powerups.LinearTransitionForce;
import io.github.alyrow.gdx.particle.rules.ParticleEmissionDuration;
import io.github.alyrow.gdx.particle.rules.ParticleEmissionNumber;
import io.github.alyrow.gdx.particle.rules.ParticleLife;

/**
 * @author alyrow
 */
public class LibraryTest extends Game {

    PhysicManager physicManager;
    boolean g = false;
    private ParticleSystem system;
    private OrthographicCamera camera;
    private SpriteBatch batch;

    public static void main(String[] args) {
        Lwjgl3ApplicationConfiguration configuration = new Lwjgl3ApplicationConfiguration();
        configuration.setTitle("NebulaDemo");
        configuration.setWindowedMode(1024, 768);
        new Lwjgl3Application(new LibraryTest(), configuration);
    }

    @Override
    public void create() {
        ParticleRules rules = new ParticleRules();
        ParticleEmissionNumber ps = new ParticleEmissionNumber(ParticleEmissionNumber.INNER_SCREEN, 8000);
        ps.setDelay(0.005f);
        rules.setNumber(ps); //One particle emitted per seconds
        rules.setLife(new ParticleLife(17, true)); //Particles life : 5s. Life will decrease when particles are outside the screen.
        rules.setDuration(new ParticleEmissionDuration(true)); //Infinite duration for the emission

        camera = new OrthographicCamera(Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
        Rectangle rectangle = new Rectangle(0, 0, Gdx.graphics.getWidth(), Gdx.graphics.getHeight());
        ParticleView view = new ParticleView(camera, rectangle);
        camera.position.set(camera.viewportWidth / 2.0f, camera.viewportHeight / 2.0f, 1.0f);
        camera.update();
        ParticleType type = new ParticleType();
        batch = new SpriteBatch();
        system = new ParticleSystem(type, view, batch);
        system.setRules(rules);
        system.setParticlesPosition(camera.viewportWidth / 2.0f - 200, camera.viewportHeight / 2.0f);
//        system.disableBlending();

        try {
            system.getModifierManager().addModifier(
                    //                new RandomPositionRectangle(camera.viewportWidth/2, camera.viewportHeight)
                    //                new RandomColors()
                    //new GradientColors(new Color(0.01f, 0.00391666666f, 0.001125f, 0.1f), new Color(0.94117647058f, 0.36862745098f, 0.10588235294f, 0.8f))
                    //                new RandomMassModifier(10,30),
                    //                new RandomChargeModifier(),
//                                    new MassProportionalLightRadius(2f)
            );
        } catch (Exception e) {
            e.printStackTrace();
        }

        physicManager = new PhysicManager();

        //physicManager.addForce(new BlackHole(3, 5, 25));
        //physicManager.addForce(new BlackLine(Line.fromTwoPoints(1,1,5,5), 5, 25));
//        physicManager.addForce(new BrownianForce(400, 2, 0.01));

        // INFINITY
        PathFollow infinity = new PathFollow("M93.9,46.4c9.3,9.5,13.8,17.9,23.5,17.9s17.5-7.8,17.5-17.5s-7.8-17.6-17.5-17.5c-9.7,0.1-13.3,7.2-22.1,17.1 c-8.9,8.8-15.7,17.9-25.4,17.9s-17.5-7.8-17.5-17.5s7.8-17.5,17.5-17.5S86.2,38.6,93.9,55.4z", 1f);
        physicManager.addForce(infinity);
        physicManager.addForce(new BrownianForce(40, 1365476841, 0.0001));
        physicManager.addForce(new LinearTransitionForce(new BrownianForce(20, 1234, 0.001), infinity, 0.01f));
//        physicManager.addForce(new PathFollow("M 0 0 L 6 0 L 3 -4 L 0 0", 1f));
//        physicManager.addForce(new Drain(500, 400, 30, 10));
        //physicManager.addForce(new ImageColour(Gdx.files.internal("test2.png")));
//        physicManager.addForce(new Fan(50, 50, 6));
        //physicManager.addForce(new LinearForce(5, 0));
//        physicManager.addForce(new PointAttract(41, 65, 1));
//        physicManager.addForce(new Revolution(15, 65, 2));
        //physicManager.addForce(new WhiteHole(600, 600, 0.001f));

        system.setPhysicManager(physicManager);

    }

    @Override
    public void render() {
        //Gdx.gl.glClearColor(0f, 0f, 0f, 1);
        Gdx.gl.glClear(GL20.GL_COLOR_BUFFER_BIT);
        batch.begin();
        system.render();
        batch.end();

        if (g) {
            physicManager.addForce(new Fan(camera.viewportWidth / 2f, camera.viewportHeight / 2f, 20));
            g = false;
        }
    }
}
